### PR TITLE
use sandboxed env

### PR DESCRIPTION
**Pull request by wolfv**
A little more security.

### CODE REVIEW

**Comment by nichmor** [comment]
it is worth to have a test were we will validate that we catch security issue?

**Review by nichmor — COMMENTED** [review]
also we need to change the return type

**Comment by wolfv** [comment]
Yeah I was trying to come up with a test but have failed so far ... the one I was thinking about mostly was about leaking env variables.

**Review by nichmor — APPROVED** [review]
got it! let's then just change the return type and merge it!

**Pull request merged**
